name: CICD Pipeline

on:
  push: 
    branches:
      - main

jobs:
  test:
    name: Perform application testing.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install Dependencies
        run: npm install

      - name: Run tests and save results
        run: |
          npm run check > test-results.txt || true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with: 
          name: test-results
          path: test-results.txt 

  deploy:
    name: Deploy Application
    runs-on: self-hosted
    needs: test
    steps:
      - name: Install nginx
        uses: sudo apt install nginx

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download test results
        uses: actions/download-artifact@v5
        with:
          name: test-results
          path: ./artifacts

      - name: Display test results
        run: cat ./artifacts/test-results.txt

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install PM2
        run: |
          npm install -g pm2

      - name: Start application in pm2
        run: |
          pm2 delete "Server" || true
          pm2 start "npm start" --name="Server"